import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/admin/require-admin'
import { prisma } from '@/lib/prisma'
import { DiscountType } from '@prisma/client'
import { autoGeneratePromotionSchema } from '@/lib/validations/admin'
import { rateLimit, getIP, createRateLimitKey } from '@/lib/rate-limit'
import { logError } from '@/lib/logger'
import { validateCsrfToken } from '@/lib/csrf'

// POST - Automatisch Promotions generieren
export async function POST(request: NextRequest) {
  const rl = await rateLimit(createRateLimitKey(getIP(request), 'admin:promotions:auto-generate'), {
    windowMs: 60_000,
    maxRequests: 5,
  })
  if (!rl.success) return NextResponse.json({ error: 'Zu viele Anfragen' }, { status: 429 })
  try {
    const authz = await requireAdmin()
    if (!authz.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: authz.status })

    const csrfError = validateCsrfToken(request)
    if (csrfError) return csrfError

    const body = await request.json()
    const parsed = autoGeneratePromotionSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Ungültige Daten', details: parsed.error.flatten().fieldErrors },
        { status: 400 }
      )
    }

    const { type, discountPercent, durationDays, categoryIds = [], productCount = 10 } = parsed.data

    const now = new Date()
    const endDate = new Date(now)
    endDate.setDate(endDate.getDate() + durationDays)

    const promotions = []

    switch (type) {
      case 'flash': {
        // Select the most popular products
        const products = await prisma.product.findMany({
          where: {
            isActive: true,
            ...(categoryIds?.length ? { categoryId: { in: categoryIds } } : {}),
          },
          orderBy: [{ rating: 'desc' }, { reviewCount: 'desc' }],
          take: productCount,
          select: { id: true, nameDe: true, price: true, categoryId: true },
        })

        const promotion = await prisma.promotion.create({
          data: {
            name: `Flash Deal - ${discountPercent}%`,
            description: `Flash-Angebot! ${discountPercent}% Rabatt auf beliebte Produkte.`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: false,
            productIds: products.map((p) => p.id),
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: `-${discountPercent}%`,
            bannerText: '⚡ Flash Deal - Begrenzte Mengen!',
            highlightColor: '#FF6B6B',
            isActive: true,
            autoGenerated: true,
          },
        })
        promotions.push(promotion)
        break
      }

      case 'weekend': {
        const promotion = await prisma.promotion.create({
          data: {
            name: 'Wochenend-Special',
            description: `Genießen Sie ${discountPercent}% Rabatt nur dieses Wochenende!`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: categoryIds?.length === 0,
            productIds: [],
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: 'WOCHENENDE',
            bannerText: '🎉 Wochenend-Sonderangebot - Begrenztes Angebot!',
            highlightColor: '#4ECCA3',
            isActive: true,
            autoGenerated: true,
          },
        })
        promotions.push(promotion)
        break
      }

      case 'clearance': {
        // Am schwächsten performende Produkte
        const products = await prisma.product.findMany({
          where: {
            isActive: true,
            ...(categoryIds?.length ? { categoryId: { in: categoryIds } } : {}),
          },
          orderBy: { rating: 'asc' },
          take: productCount,
          select: { id: true },
        })

        const promotion = await prisma.promotion.create({
          data: {
            name: 'Ausverkauf',
            description: `Lagerabverkauf mit bis zu ${discountPercent}% Rabatt!`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: false,
            productIds: products.map((p) => p.id),
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: 'RESTPOSTEN',
            bannerText: '🏷️ Ausverkauf - Sonderpreise!',
            highlightColor: '#FFA500',
            isActive: true,
            autoGenerated: true,
          },
        })
        promotions.push(promotion)
        break
      }

      case 'new-arrival': {
        const promotion = await prisma.promotion.create({
          data: {
            name: 'Neuheiten',
            description: `Entdecken Sie unsere Neuheiten mit ${discountPercent}% Willkommensrabatt!`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: false,
            productIds: [],
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: 'NEU',
            bannerText: '✨ Neuheiten - Einführungsangebot!',
            highlightColor: '#9B59B6',
            isActive: true,
            autoGenerated: true,
          },
        })
        promotions.push(promotion)
        break
      }
    }

    return NextResponse.json({ promotions, count: promotions.length })
  } catch (error) {
    logError('Error auto-generating promotions:', error)
    return NextResponse.json({ error: 'Failed to generate promotions' }, { status: 500 })
  }
}
