import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/admin/require-admin'
import { auditLog } from '@/lib/admin/audit'
import { prisma } from '@/lib/prisma'
import { DiscountType } from '@prisma/client'
import { autoGeneratePromotionSchema } from '@/lib/validations/admin'

// POST - Générer automatiquement des promotions
export async function POST(request: NextRequest) {
  try {
    const authz = await requireAdmin()
    if (!authz.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: authz.status })

    const body = await request.json()
    const parsed = autoGeneratePromotionSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Ungültige Daten', details: parsed.error.flatten().fieldErrors },
        { status: 400 }
      )
    }

    const { type, discountPercent, durationDays, categoryIds = [], productCount = 10 } = parsed.data

    const now = new Date()
    const endDate = new Date(now)
    endDate.setDate(endDate.getDate() + durationDays)

    let promotions = []

    switch (type) {
      case 'flash': {
        // Sélectionner les produits les plus populaires
        const products = await prisma.product.findMany({
          where: {
            isActive: true,
            ...(categoryIds?.length ? { categoryId: { in: categoryIds } } : {})
          },
          orderBy: [{ rating: 'desc' }, { reviewCount: 'desc' }],
          take: productCount,
          select: { id: true, nameDe: true, price: true, categoryId: true }
        })

        const promotion = await prisma.promotion.create({
          data: {
            name: `Flash Deal - ${discountPercent}%`,
            description: `Offre flash limitée! ${discountPercent}% de réduction sur les produits populaires.`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: false,
            productIds: products.map(p => p.id),
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: `-${discountPercent}%`,
            bannerText: '⚡ Flash Deal - Quantités limitées!',
            highlightColor: '#FF6B6B',
            isActive: true,
            autoGenerated: true
          }
        })
        promotions.push(promotion)
        break
      }

      case 'weekend': {
        const promotion = await prisma.promotion.create({
          data: {
            name: 'Weekend Special',
            description: `Profitez de ${discountPercent}% de réduction ce week-end uniquement!`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: categoryIds?.length === 0,
            productIds: [],
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: 'WEEKEND',
            bannerText: '🎉 Spécial Week-end - Offre limitée!',
            highlightColor: '#4ECCA3',
            isActive: true,
            autoGenerated: true
          }
        })
        promotions.push(promotion)
        break
      }

      case 'clearance': {
        // Produits avec stock élevé
        const products = await prisma.product.findMany({
          where: {
            isActive: true,
            stock: { gt: 20 },
            ...(categoryIds?.length ? { categoryId: { in: categoryIds } } : {})
          },
          orderBy: { stock: 'desc' },
          take: productCount,
          select: { id: true }
        })

        const promotion = await prisma.promotion.create({
          data: {
            name: 'Déstockage',
            description: `Liquidation de stock jusqu'à ${discountPercent}% de réduction!`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: false,
            productIds: products.map(p => p.id),
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: 'DESTOCKAGE',
            bannerText: '🏷️ Déstockage - Prix cassés!',
            highlightColor: '#FFA500',
            isActive: true,
            autoGenerated: true
          }
        })
        promotions.push(promotion)
        break
      }

      case 'new-arrival': {
        const promotion = await prisma.promotion.create({
          data: {
            name: 'Nouveautés',
            description: `Découvrez nos nouveautés avec ${discountPercent}% de bienvenue!`,
            discountType: DiscountType.PERCENTAGE,
            discountValue: discountPercent,
            isGlobal: false,
            productIds: [],
            categoryIds: categoryIds || [],
            startDate: now,
            endDate,
            badge: 'NEW',
            bannerText: '✨ Nouveautés - Offre de lancement!',
            highlightColor: '#9B59B6',
            isActive: true,
            autoGenerated: true
          }
        })
        promotions.push(promotion)
        break
      }
    }

    return NextResponse.json({ promotions, count: promotions.length })
  } catch (error) {
    console.error('Error auto-generating promotions:', error)
    return NextResponse.json(
      { error: 'Failed to generate promotions' },
      { status: 500 }
    )
  }
}
