'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import PromotionForm from '../../_components/promotion-form'

interface Promotion {
  id: string
  name: string
  description: string | null
  code: string | null
  isCoupon: boolean
  discountType: 'PERCENTAGE' | 'FIXED_AMOUNT'
  discountValue: number
  isGlobal: boolean
  productIds: string[]
  categoryIds: string[]
  startDate: string
  endDate: string
  minOrderAmount: number | null
  maxDiscount: number | null
  usageLimit: number | null
  badge: string | null
  bannerText: string | null
  highlightColor: string | null
  isActive: boolean
  autoGenerated: boolean
}

export default function EditPromotionPage() {
  const params = useParams()
  const [promotion, setPromotion] = useState<Promotion | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchPromotion()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fetchPromotion = async () => {
    try {
      const response = await fetch(`/api/admin/promotions/${params.id}`)
      if (response.ok) {
        const data = await response.json()
        setPromotion(data)
      }
    } catch (error) {
      console.error('Error fetching promotion:', error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-t-2 border-[#4ECCA3]"></div>
      </div>
    )
  }

  if (!promotion) {
    return (
      <div className="py-12 text-center">
        <p className="text-gray-400">Aktion nicht gefunden</p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Aktion bearbeiten</h1>
        <p className="mt-1 text-gray-400">Einstellungen von {promotion.name} ändern</p>
      </div>

      <PromotionForm promotion={promotion} />
    </div>
  )
}
