import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { createPromotionSchema } from '@/lib/validations/promotion'
import { Prisma } from '@prisma/client'
import { requireAdmin } from '@/lib/admin/require-admin'
import { auditLog } from '@/lib/admin/audit'
import { rateLimit, getIP, createRateLimitKey } from '@/lib/rate-limit'
import { logError } from '@/lib/logger'

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const productId = searchParams.get('productId')
    const categoryId = searchParams.get('categoryId')
    const includeExpiredRequested = searchParams.get('includeExpired') === 'true'
    let includeExpired = false
    if (includeExpiredRequested) {
      const session = await auth()
      includeExpired = Boolean(session?.user && session.user.role === 'ADMIN')
    }
    
    const now = new Date()
    
    const where: Prisma.PromotionWhereInput = {}
    
    if (!includeExpired) {
      where.isActive = true
      where.startDate = { lte: now }
      where.endDate = { gt: now }
    }
    
    if (productId || categoryId) {
      const orConditions: Prisma.PromotionWhereInput[] = [{ isGlobal: true }]
      if (productId) orConditions.push({ productIds: { has: productId } })
      if (categoryId) orConditions.push({ categoryIds: { has: categoryId } })
      where.OR = orConditions
    }
    
    const promotions = await prisma.promotion.findMany({
      where,
      orderBy: [
        { discountValue: 'desc' },
        { endDate: 'asc' },
      ],
    })
    
    const response = NextResponse.json(promotions)
    response.headers.set(
      "Cache-Control",
      includeExpired ? "no-store" : "public, s-maxage=60, stale-while-revalidate=300"
    )
    return response
  } catch (error) {
    logError('Error fetching promotions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch promotions' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const authz = await requireAdmin()
    if (!authz.ok) return NextResponse.json({ error: 'Forbidden', details: authz.status }, { status: authz.status })

    const rl = await rateLimit(createRateLimitKey(getIP(request), 'promotions:create'), { windowMs: 60_000, maxRequests: 10 })
    if (!rl.success) return NextResponse.json({ error: 'Zu viele Anfragen' }, { status: 429 })

    const body = await request.json()
    const validationResult = createPromotionSchema.safeParse(body)

    if (!validationResult.success) {
      return NextResponse.json(
        { 
          error: 'Validation failed', 
          details: validationResult.error.flatten().fieldErrors 
        },
        { status: 400 }
      )
    }

    const validatedData = validationResult.data

    const promotion = await prisma.promotion.create({
      data: {
        name: validatedData.name,
        code: validatedData.code,
        description: validatedData.description,
        discountType: validatedData.discountType,
        discountValue: new Prisma.Decimal(validatedData.discountValue),
        isGlobal: validatedData.isGlobal,
        productIds: validatedData.productIds,
        categoryIds: validatedData.categoryIds,
        startDate: validatedData.startDate,
        endDate: validatedData.endDate,
        minOrderAmount: validatedData.minOrderAmount ? new Prisma.Decimal(validatedData.minOrderAmount) : null,
        maxDiscount: validatedData.maxDiscount ? new Prisma.Decimal(validatedData.maxDiscount) : null,
        usageLimit: validatedData.usageLimit,
        badge: validatedData.badge,
        bannerText: validatedData.bannerText,
        highlightColor: validatedData.highlightColor,
        autoGenerated: false,
        usageCount: 0,
        isActive: true,
      },
    })

    await auditLog({
      action: 'CREATE',
      entityType: 'Promotion',
      entityId: promotion.id,
      userId: authz.session.user.id,
      newValues: { name: promotion.name, code: promotion.code, discountValue: promotion.discountValue, discountType: promotion.discountType },
      ipAddress: request.headers.get('x-forwarded-for'),
      userAgent: request.headers.get('user-agent'),
    })

    return NextResponse.json(promotion, { status: 201 })
  } catch (error) {
    logError('Error creating promotion:', error)
    return NextResponse.json(
      { error: 'Failed to create promotion' },
      { status: 500 }
    )
  }
}
