import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { createPromotionSchema, getPromotionsQuerySchema } from '@/lib/validations/promotion'
import { Prisma } from '@prisma/client'

/**
 * GET: Fetch active promotions
 * Query params: productId, categoryId
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const productId = searchParams.get('productId')
    const categoryId = searchParams.get('categoryId')
    const includeExpired = searchParams.get('includeExpired') === 'true'
    
    const now = new Date()
    
    const where: Prisma.PromotionWhereInput = {}
    
    if (!includeExpired) {
      where.isActive = true
      where.startDate = { lte: now }
      where.endDate = { gt: now }
    }
    
    // Filter by product or category
    if (productId) {
      where.OR = [
        { isGlobal: true },
        { productIds: { has: productId } },
      ]
      if (categoryId) {
        where.OR.push({ categoryIds: { has: categoryId } })
      }
    }
    
    const promotions = await prisma.promotion.findMany({
      where,
      orderBy: [
        { discountValue: 'desc' },
        { endDate: 'asc' },
      ],
    })
    
    return NextResponse.json(promotions)
  } catch (error) {
    console.error('Error fetching promotions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch promotions' },
      { status: 500 }
    )
  }
}

/**
 * POST: Manually create a promotion (admin only)
 * Requires ADMIN role authentication
 */
export async function POST(request: NextRequest) {
  try {
    // 1. Vérification authentification
    const session = await auth()
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized - Please sign in' },
        { status: 401 }
      )
    }

    // 2. Vérification rôle ADMIN
    if (session.user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Forbidden - Admin access required' },
        { status: 403 }
      )
    }

    // 3. Parsing et validation du body
    const body = await request.json()
    const validationResult = createPromotionSchema.safeParse(body)

    if (!validationResult.success) {
      return NextResponse.json(
        { 
          error: 'Validation failed', 
          details: validationResult.error.flatten().fieldErrors 
        },
        { status: 400 }
      )
    }

    const validatedData = validationResult.data

    // 4. Création de la promotion avec données validées
    const promotion = await prisma.promotion.create({
      data: {
        name: validatedData.name,
        code: validatedData.code,
        description: validatedData.description,
        discountType: validatedData.discountType,
        discountValue: new Prisma.Decimal(validatedData.discountValue),
        isGlobal: validatedData.isGlobal,
        productIds: validatedData.productIds,
        categoryIds: validatedData.categoryIds,
        startDate: validatedData.startDate,
        endDate: validatedData.endDate,
        minOrderAmount: validatedData.minOrderAmount ? new Prisma.Decimal(validatedData.minOrderAmount) : null,
        maxDiscount: validatedData.maxDiscount ? new Prisma.Decimal(validatedData.maxDiscount) : null,
        usageLimit: validatedData.usageLimit,
        badge: validatedData.badge,
        bannerText: validatedData.bannerText,
        highlightColor: validatedData.highlightColor,
        autoGenerated: false,
        usageCount: 0,
        isActive: true,
      },
    })

    return NextResponse.json(promotion, { status: 201 })
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred'
    console.error('Error creating promotion:', errorMessage)
    return NextResponse.json(
      { error: 'Failed to create promotion', message: errorMessage },
      { status: 500 }
    )
  }
}
