import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

/**
 * GET: Fetch active promotions
 * Query params: productId, categoryId
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const productId = searchParams.get('productId')
    const categoryId = searchParams.get('categoryId')
    const includeExpired = searchParams.get('includeExpired') === 'true'
    
    const now = new Date()
    
    const where: any = {}
    
    if (!includeExpired) {
      where.isActive = true
      where.startDate = { lte: now }
      where.endDate = { gt: now }
    }
    
    // Filter by product or category
    if (productId) {
      where.OR = [
        { isGlobal: true },
        { productIds: { has: productId } },
      ]
      if (categoryId) {
        where.OR.push({ categoryIds: { has: categoryId } })
      }
    }
    
    const promotions = await prisma.promotion.findMany({
      where,
      orderBy: [
        { discountValue: 'desc' },
        { endDate: 'asc' },
      ],
    })
    
    return NextResponse.json(promotions)
  } catch (error) {
    console.error('Error fetching promotions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch promotions' },
      { status: 500 }
    )
  }
}

/**
 * POST: Manually create a promotion (admin only)
 */
export async function POST(request: NextRequest) {
  try {
    // TODO: Add admin authentication
    const body = await request.json()
    
    const promotion = await prisma.promotion.create({
      data: {
        ...body,
        autoGenerated: false,
      },
    })
    
    return NextResponse.json(promotion)
  } catch (error) {
    console.error('Error creating promotion:', error)
    return NextResponse.json(
      { error: 'Failed to create promotion' },
      { status: 500 }
    )
  }
}
