import { prisma } from '@/lib/prisma'
import { addDays, addHours, setHours, setMinutes } from 'date-fns'

// Configuration for random promotions
const PROMOTION_CONFIG = {
  // Frequency: Chance to create a promotion on each check (0-1)
  DAILY_CHANCE: 0.3, // 30% chance per day
  WEEKEND_BOOST: 0.6, // 60% chance on weekends
  
  // Discount ranges
  MIN_PERCENTAGE: 5,
  MAX_PERCENTAGE: 25,
  MIN_FIXED_AMOUNT: 5,
  MAX_FIXED_AMOUNT: 50,
  
  // Duration ranges (hours)
  MIN_DURATION_HOURS: 24,
  MAX_DURATION_HOURS: 72,
  
  // Weekend special duration (longer)
  WEEKEND_MIN_DURATION: 48,
  WEEKEND_MAX_DURATION: 96,
}

// Flash deal names (German)
const FLASH_DEAL_NAMES = [
  '⚡ Blitzangebot',
  '🔥 Heißer Deal',
  '⏰ Nur für kurze Zeit',
  '🎯 Top-Angebot',
  '💰 Spar-Chance',
  '🎁 Überraschungs-Rabatt',
  '⭐ Tipp des Tages',
  '🏷️ Knaller-Preis',
]

// Weekend special names
const WEEKEND_NAMES = [
  '🌟 Wochenend-Special',
  '🎉 Samstags-Schnäppchen',
  '🌙 Sonntags-Sale',
  '🍷 Wochenend-Vorteil',
  '🎯 Weekend-Deal',
]

// Banner texts (German)
const BANNER_TEXTS = [
  'Nur noch wenige Stunden!',
  'Begrenzte Zeit – Greifen Sie zu!',
  'Heute besonders günstig!',
  'Schnell sein lohnt sich!',
  'Nur solange der Vorrat reicht!',
  'Exklusiv für Sie!',
]

/**
 * Check if we should create a random promotion
 * Called by cron job or API route
 */
export async function checkAndCreateRandomPromotion(): Promise<boolean> {
  const now = new Date()
  const isWeekend = now.getDay() === 0 || now.getDay() === 6
  
  // Check if there's already an active auto-generated promotion
  const activePromotions = await prisma.promotion.count({
    where: {
      isActive: true,
      autoGenerated: true,
      endDate: { gt: now },
    },
  })
  
  // Don't create if there's already 2+ active promotions
  if (activePromotions >= 2) {
    console.log('Already have', activePromotions, 'active promotions. Skipping.')
    return false
  }
  
  // Determine chance
  const chance = isWeekend ? PROMOTION_CONFIG.WEEKEND_BOOST : PROMOTION_CONFIG.DAILY_CHANCE
  
  // Roll the dice
  if (Math.random() > chance) {
    console.log('No promotion this time (chance:', chance, ')')
    return false
  }
  
  // Create the promotion
  await createRandomPromotion(isWeekend)
  return true
}

/**
 * Create a random promotion with randomized parameters
 */
async function createRandomPromotion(isWeekend: boolean): Promise<void> {
  const now = new Date()
  
  // Random discount type (80% percentage, 20% fixed)
  const discountType = Math.random() < 0.8 ? 'PERCENTAGE' : 'FIXED_AMOUNT'
  
  // Random discount value
  let discountValue: number
  if (discountType === 'PERCENTAGE') {
    discountValue = randomInt(PROMOTION_CONFIG.MIN_PERCENTAGE, PROMOTION_CONFIG.MAX_PERCENTAGE)
    // Round to nearest 5 for cleaner display (5, 10, 15, 20, 25)
    discountValue = Math.round(discountValue / 5) * 5
  } else {
    discountValue = randomInt(PROMOTION_CONFIG.MIN_FIXED_AMOUNT, PROMOTION_CONFIG.MAX_FIXED_AMOUNT)
    // Round to nearest 5 or 10
    discountValue = Math.round(discountValue / 5) * 5
  }
  
  // Random duration
  const minDuration = isWeekend ? PROMOTION_CONFIG.WEEKEND_MIN_DURATION : PROMOTION_CONFIG.MIN_DURATION_HOURS
  const maxDuration = isWeekend ? PROMOTION_CONFIG.WEEKEND_MAX_DURATION : PROMOTION_CONFIG.MAX_DURATION_HOURS
  const durationHours = randomInt(minDuration, maxDuration)
  
  // Start now or in a few hours (random delay 0-4 hours)
  const delayHours = Math.random() < 0.7 ? 0 : randomInt(1, 4)
  const startDate = addHours(now, delayHours)
  const endDate = addHours(startDate, durationHours)
  
  // Random scope (70% specific products, 30% global)
  const isGlobal = Math.random() < 0.3
  
  let productIds: string[] = []
  let categoryIds: string[] = []
  
  if (!isGlobal) {
    // Get random products
    const products = await prisma.product.findMany({
      where: { isActive: true },
      select: { id: true },
      take: 100,
    })
    
    if (products.length > 0) {
      // Pick 3-10 random products
      const numProducts = randomInt(3, Math.min(10, products.length))
      const shuffled = products.sort(() => 0.5 - Math.random())
      productIds = shuffled.slice(0, numProducts).map(p => p.id)
    }
  }
  
  // Select name and badge
  const namePool = isWeekend ? WEEKEND_NAMES : FLASH_DEAL_NAMES
  const name = namePool[randomInt(0, namePool.length - 1)]
  
  const badge = discountType === 'PERCENTAGE' 
    ? `-${discountValue}%` 
    : `-${discountValue}€`
  
  const bannerText = BANNER_TEXTS[randomInt(0, BANNER_TEXTS.length - 1)]
  
  // Color: red for urgency on short deals, brand color for longer
  const highlightColor = durationHours <= 24 ? '#E17055' : '#4ECCA3'
  
  // Create the promotion
  const promotion = await prisma.promotion.create({
    data: {
      name,
      description: `Auto-generated ${isWeekend ? 'weekend' : 'flash'} deal`,
      discountType,
      discountValue,
      isGlobal,
      productIds,
      categoryIds,
      startDate,
      endDate,
      badge,
      bannerText,
      highlightColor,
      autoGenerated: true,
    },
  })
  
  console.log('Created random promotion:', {
    id: promotion.id,
    name: promotion.name,
    discount: badge,
    duration: `${durationHours}h`,
    products: productIds.length || 'global',
  })
}

/**
 * Get currently active promotions for a product
 */
export async function getActivePromotionsForProduct(productId: string, categoryId?: string): Promise<any[]> {
  const now = new Date()
  
  const promotions = await prisma.promotion.findMany({
    where: {
      isActive: true,
      startDate: { lte: now },
      endDate: { gt: now },
      OR: [
        { isGlobal: true },
        { productIds: { has: productId } },
        ...(categoryId ? [{ categoryIds: { has: categoryId } }] : []),
      ],
    },
    orderBy: [
      { discountValue: 'desc' },
      { endDate: 'asc' },
    ],
  })
  
  return promotions
}

/**
 * Calculate discounted price
 */
export function calculateDiscountedPrice(
  originalPrice: number, 
  discountType: string, 
  discountValue: number,
  maxDiscount?: number | null
): { price: number; discount: number } {
  let discount = 0
  
  if (discountType === 'PERCENTAGE') {
    discount = originalPrice * (discountValue / 100)
  } else {
    discount = discountValue
  }
  
  // Apply max discount cap if set
  if (maxDiscount && discount > maxDiscount) {
    discount = maxDiscount
  }
  
  const price = Math.max(0, originalPrice - discount)
  
  return { price, discount }
}

/**
 * Cleanup expired promotions
 */
export async function cleanupExpiredPromotions(): Promise<number> {
  const now = new Date()
  
  const result = await prisma.promotion.updateMany({
    where: {
      isActive: true,
      endDate: { lt: now },
    },
    data: {
      isActive: false,
    },
  })
  
  console.log('Deactivated', result.count, 'expired promotions')
  return result.count
}

/**
 * Get active banner promotion (the best one for display)
 */
export async function getBannerPromotion(): Promise<any | null> {
  const now = new Date()
  
  const promotion = await prisma.promotion.findFirst({
    where: {
      isActive: true,
      startDate: { lte: now },
      endDate: { gt: now },
      bannerText: { not: null },
    },
    orderBy: [
      { discountValue: 'desc' },
    ],
  })
  
  return promotion
}

// Utility: Random integer between min and max (inclusive)
function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min
}
