import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/admin/require-admin'
import { auditLog } from '@/lib/admin/audit'
import { prisma } from '@/lib/prisma'
import { createPromotionAdminSchema } from '@/lib/validations/admin'

// GET - Liste toutes les promotions
export async function GET() {
  try {
    const authz = await requireAdmin()
    if (!authz.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: authz.status })

    const promotions = await prisma.promotion.findMany({
      orderBy: { createdAt: 'desc' }
    })

    return NextResponse.json(promotions)
  } catch (error) {
    console.error('Error fetching promotions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch promotions' },
      { status: 500 }
    )
  }
}

// POST - Créer une nouvelle promotion
export async function POST(request: NextRequest) {
  try {
    const authz = await requireAdmin()
    if (!authz.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: authz.status })

    const body = await request.json()
    const parsed = createPromotionAdminSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Ungültige Daten', details: parsed.error.flatten().fieldErrors },
        { status: 400 }
      )
    }

    const data = parsed.data
    const promotion = await prisma.promotion.create({
      data: {
        ...data,
        startDate: new Date(data.startDate),
        endDate: new Date(data.endDate),
        autoGenerated: false,
      }
    })

    await auditLog({
      action: 'CREATE',
      entityType: 'Promotion',
      entityId: promotion.id,
      userId: authz.session.user.id,
      newValues: promotion,
      ipAddress: request.headers.get('x-forwarded-for'),
      userAgent: request.headers.get('user-agent'),
    })

    return NextResponse.json(promotion)
  } catch (error) {
    console.error('Error creating promotion:', error)
    return NextResponse.json(
      { error: 'Failed to create promotion' },
      { status: 500 }
    )
  }
}
