import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

// GET - Liste toutes les promotions
export async function GET() {
  try {
    const session = await auth()
    if (!session?.user || session.user.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const promotions = await prisma.promotion.findMany({
      orderBy: { createdAt: 'desc' }
    })

    return NextResponse.json(promotions)
  } catch (error) {
    console.error('Error fetching promotions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch promotions' },
      { status: 500 }
    )
  }
}

// POST - Créer une nouvelle promotion
export async function POST(request: NextRequest) {
  try {
    const session = await auth()
    if (!session?.user || session.user.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const data = await request.json()

    const promotion = await prisma.promotion.create({
      data: {
        name: data.name,
        description: data.description,
        discountType: data.discountType,
        discountValue: data.discountValue,
        isGlobal: data.isGlobal,
        productIds: data.productIds || [],
        categoryIds: data.categoryIds || [],
        startDate: new Date(data.startDate),
        endDate: new Date(data.endDate),
        minOrderAmount: data.minOrderAmount,
        maxDiscount: data.maxDiscount,
        usageLimit: data.usageLimit,
        badge: data.badge,
        bannerText: data.bannerText,
        highlightColor: data.highlightColor,
        isActive: data.isActive,
        autoGenerated: false // Manuelle depuis l'admin
      }
    })

    return NextResponse.json(promotion)
  } catch (error) {
    console.error('Error creating promotion:', error)
    return NextResponse.json(
      { error: 'Failed to create promotion' },
      { status: 500 }
    )
  }
}
