'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import { 
  Plus, 
  Search, 
  Edit2, 
  Trash2, 
  Calendar, 
  Percent, 
  Tag,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Sparkles,
  Clock
} from 'lucide-react'

interface Promotion {
  id: string
  name: string
  description: string | null
  discountType: 'PERCENTAGE' | 'FIXED_AMOUNT'
  discountValue: number
  isGlobal: boolean
  isActive: boolean
  autoGenerated: boolean
  startDate: string
  endDate: string
  badge: string | null
  bannerText: string | null
  highlightColor?: string | null
  usageCount: number
  usageLimit: number | null
}

export default function PromotionsPage() {
  const [promotions, setPromotions] = useState<Promotion[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [filter, setFilter] = useState<'all' | 'active' | 'inactive' | 'auto'>('all')
  const router = useRouter()

  useEffect(() => {
    fetchPromotions()
  }, [])

  const fetchPromotions = async () => {
    try {
      const response = await fetch('/api/admin/promotions')
      if (response.ok) {
        const data = await response.json()
        setPromotions(data)
      }
    } catch (error) {
      console.error('Error fetching promotions:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Sind Sie sicher, dass Sie diese Aktion löschen möchten?')) return

    try {
      const response = await fetch(`/api/admin/promotions/${id}`, {
        method: 'DELETE'
      })

      if (response.ok) {
        setPromotions(promotions.filter(p => p.id !== id))
      }
    } catch (error) {
      console.error('Error deleting promotion:', error)
    }
  }

  const toggleStatus = async (id: string, currentStatus: boolean) => {
    try {
      const promotion = promotions.find(p => p.id === id)
      if (!promotion) return

      const response = await fetch(`/api/admin/promotions/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...promotion,
          isActive: !currentStatus
        })
      })

      if (response.ok) {
        setPromotions(promotions.map(p => 
          p.id === id ? { ...p, isActive: !currentStatus } : p
        ))
      }
    } catch (error) {
      console.error('Error updating promotion:', error)
    }
  }

  const isExpired = (endDate: string) => {
    return new Date(endDate) < new Date()
  }

  const filteredPromotions = promotions.filter(promotion => {
    const matchesSearch = promotion.name.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesFilter = 
      filter === 'all' ? true :
      filter === 'active' ? promotion.isActive && !isExpired(promotion.endDate) :
      filter === 'inactive' ? !promotion.isActive || isExpired(promotion.endDate) :
      filter === 'auto' ? promotion.autoGenerated : true
    return matchesSearch && matchesFilter
  })

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-[#4ECCA3]"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Aktionen</h1>
          <p className="text-gray-400 mt-1">Verwalten Sie Rabatte und Sonderangebote</p>
        </div>
        <div className="flex gap-3">
          <Link
            href="/admin/promotions/auto-generate"
            className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg hover:from-purple-600 hover:to-pink-600 transition-all"
          >
            <Sparkles className="w-4 h-4" />
            <span>Auto-generieren</span>
          </Link>
          <Link
            href="/admin/promotions/new"
            className="flex items-center gap-2 px-4 py-2 bg-[#4ECCA3] text-[#1A1A1A] rounded-lg hover:bg-[#3DBB92] transition-all"
          >
            <Plus className="w-4 h-4" />
            <span>Neue Aktion</span>
          </Link>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div className="bg-[#2A2A2A] rounded-xl p-4 border border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-[#4ECCA3]/20 flex items-center justify-center">
              <Tag className="w-5 h-5 text-[#4ECCA3]" />
            </div>
            <div>
              <p className="text-gray-400 text-sm">Gesamt</p>
              <p className="text-white text-xl font-bold">{promotions.length}</p>
            </div>
          </div>
        </div>
        <div className="bg-[#2A2A2A] rounded-xl p-4 border border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-green-500/20 flex items-center justify-center">
              <CheckCircle2 className="w-5 h-5 text-green-500" />
            </div>
            <div>
              <p className="text-gray-400 text-sm">Aktiv</p>
              <p className="text-white text-xl font-bold">
                {promotions.filter(p => p.isActive && !isExpired(p.endDate)).length}
              </p>
            </div>
          </div>
        </div>
        <div className="bg-[#2A2A2A] rounded-xl p-4 border border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-yellow-500/20 flex items-center justify-center">
              <Clock className="w-5 h-5 text-yellow-500" />
            </div>
            <div>
              <p className="text-gray-400 text-sm">Expirées</p>
              <p className="text-white text-xl font-bold">
                {promotions.filter(p => isExpired(p.endDate)).length}
              </p>
            </div>
          </div>
        </div>
        <div className="bg-[#2A2A2A] rounded-xl p-4 border border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-purple-500/20 flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-purple-500" />
            </div>
            <div>
              <p className="text-gray-400 text-sm">Auto-generiert</p>
              <p className="text-white text-xl font-bold">
                {promotions.filter(p => p.autoGenerated).length}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            placeholder="Aktion suchen..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 bg-[#2A2A2A] border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-[#4ECCA3]"
          />
        </div>
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value as any)}
          className="px-4 py-2 bg-[#2A2A2A] border border-white/10 rounded-lg text-white focus:outline-none focus:border-[#4ECCA3]"
        >
          <option value="all">Alle</option>
          <option value="active">Aktiv</option>
          <option value="inactive">Inaktiv</option>
          <option value="auto">Auto-generiert</option>
        </select>
      </div>

      {/* Promotions List */}
      <div className="bg-[#2A2A2A] rounded-xl border border-white/5 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-[#1A1A1A] border-b border-white/5">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-medium text-gray-400">Aktion</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-gray-400">Rabatt</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-gray-400">Zeitraum</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-gray-400">Status</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-gray-400">Nutzung</th>
                <th className="px-6 py-4 text-right text-sm font-medium text-gray-400">Aktionen</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {filteredPromotions.map((promotion) => (
                <motion.tr
                  key={promotion.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="hover:bg-white/5"
                >
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div 
                        className="w-10 h-10 rounded-lg flex items-center justify-center text-white font-bold text-sm"
                        style={{ backgroundColor: promotion.highlightColor || '#4ECCA3' }}
                      >
                        {promotion.badge?.slice(0, 3) || '%'}
                      </div>
                      <div>
                        <p className="text-white font-medium flex items-center gap-2">
                          {promotion.name}
                          {promotion.autoGenerated && (
                            <Sparkles className="w-4 h-4 text-purple-400" />
                          )}
                        </p>
                        {promotion.bannerText && (
                          <p className="text-gray-400 text-sm">{promotion.bannerText}</p>
                        )}
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <Percent className="w-4 h-4 text-[#4ECCA3]" />
                      <span className="text-white">
                        {promotion.discountType === 'PERCENTAGE' 
                          ? `${promotion.discountValue}%` 
                          : `${promotion.discountValue}€`}
                      </span>
                    </div>
                    {promotion.isGlobal && (
                      <span className="text-xs text-gray-500">Global</span>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2 text-gray-400">
                      <Calendar className="w-4 h-4" />
                      <span className="text-sm">
                        {new Date(promotion.startDate).toLocaleDateString('de-DE')} - {new Date(promotion.endDate).toLocaleDateString('de-DE')}
                      </span>
                    </div>
                    {isExpired(promotion.endDate) && (
                      <span className="text-xs text-red-400">Abgelaufen</span>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <button
                      onClick={() => toggleStatus(promotion.id, promotion.isActive)}
                      className={`flex items-center gap-1 px-3 py-1 rounded-full text-xs font-medium transition-all ${
                        promotion.isActive && !isExpired(promotion.endDate)
                          ? 'bg-green-500/20 text-green-400' 
                          : 'bg-gray-500/20 text-gray-400'
                      }`}
                    >
                      {promotion.isActive && !isExpired(promotion.endDate) ? (
                        <><CheckCircle2 className="w-3 h-3" /> Aktiv</>
                      ) : (
                        <><XCircle className="w-3 h-3" /> Inaktiv</>
                      )}
                    </button>
                  </td>
                  <td className="px-6 py-4">
                    <span className="text-white">
                      {promotion.usageCount}
                      {promotion.usageLimit && ` / ${promotion.usageLimit}`}
                    </span>
                    <span className="text-gray-500 text-xs ml-1">utilisations</span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center justify-end gap-2">
                      <Link
                        href={`/admin/promotions/${promotion.id}/edit`}
                        className="p-2 text-gray-400 hover:text-[#4ECCA3] hover:bg-[#4ECCA3]/10 rounded-lg transition-all"
                      >
                        <Edit2 className="w-4 h-4" />
                      </Link>
                      <button
                        onClick={() => handleDelete(promotion.id)}
                        className="p-2 text-gray-400 hover:text-red-400 hover:bg-red-400/10 rounded-lg transition-all"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
        {filteredPromotions.length === 0 && (
          <div className="text-center py-12">
            <AlertCircle className="w-12 h-12 text-gray-500 mx-auto mb-4" />
            <p className="text-gray-400">Keine Aktionen gefunden</p>
          </div>
        )}
      </div>
    </div>
  )
}
