'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import {
  Plus,
  Search,
  Edit2,
  Trash2,
  Calendar,
  Percent,
  Tag,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Sparkles,
  Clock,
} from 'lucide-react'
import { logError } from '@/lib/logger'

interface Promotion {
  id: string
  name: string
  description: string | null
  discountType: 'PERCENTAGE' | 'FIXED_AMOUNT'
  discountValue: number
  isGlobal: boolean
  isActive: boolean
  autoGenerated: boolean
  isCoupon: boolean
  code: string | null
  startDate: string
  endDate: string
  badge: string | null
  bannerText: string | null
  highlightColor?: string | null
  usageCount: number
  usageLimit: number | null
}

export default function PromotionsPage() {
  const [promotions, setPromotions] = useState<Promotion[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [filter, setFilter] = useState<'all' | 'active' | 'inactive' | 'auto'>('all')
  useEffect(() => {
    fetchPromotions()
  }, [])

  const fetchPromotions = async () => {
    try {
      const response = await fetch('/api/admin/promotions')
      if (response.ok) {
        const data = await response.json()
        setPromotions(data)
      }
    } catch (error) {
      logError('Error fetching promotions:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Sind Sie sicher, dass Sie diese Aktion löschen möchten?')) return

    try {
      const response = await fetch(`/api/admin/promotions/${id}`, {
        method: 'DELETE',
      })

      if (response.ok) {
        setPromotions(promotions.filter((p) => p.id !== id))
      }
    } catch (error) {
      logError('Error deleting promotion:', error)
    }
  }

  const toggleStatus = async (id: string, currentStatus: boolean) => {
    try {
      const promotion = promotions.find((p) => p.id === id)
      if (!promotion) return

      const response = await fetch(`/api/admin/promotions/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...promotion,
          isActive: !currentStatus,
        }),
      })

      if (response.ok) {
        setPromotions(promotions.map((p) => (p.id === id ? { ...p, isActive: !currentStatus } : p)))
      }
    } catch (error) {
      logError('Error updating promotion:', error)
    }
  }

  const isExpired = (endDate: string) => {
    return new Date(endDate) < new Date()
  }

  const filteredPromotions = promotions.filter((promotion) => {
    const matchesSearch = promotion.name.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesFilter =
      filter === 'all'
        ? true
        : filter === 'active'
          ? promotion.isActive && !isExpired(promotion.endDate)
          : filter === 'inactive'
            ? !promotion.isActive || isExpired(promotion.endDate)
            : filter === 'auto'
              ? promotion.autoGenerated
              : true
    return matchesSearch && matchesFilter
  })

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-t-2 border-primary"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Aktionen</h1>
          <p className="mt-1 text-slate-600">Verwalten Sie Rabatte und Sonderangebote</p>
        </div>
        <div className="flex gap-3">
          <Link
            href="/admin/promotions/auto-generate"
            className="flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-white transition-all hover:bg-purple-700"
          >
            <Sparkles className="h-4 w-4" />
            <span>Auto-generieren</span>
          </Link>
          <Link
            href="/admin/promotions/new"
            className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-white transition-all hover:bg-primary/90"
          >
            <Plus className="h-4 w-4" />
            <span>Neue Aktion</span>
          </Link>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-4">
        <div className="rounded-xl border border-slate-200 bg-white p-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
              <Tag className="h-5 w-5 text-primary" />
            </div>
            <div>
              <p className="text-sm text-slate-500">Gesamt</p>
              <p className="text-xl font-bold text-slate-900">{promotions.length}</p>
            </div>
          </div>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-green-50">
              <CheckCircle2 className="h-5 w-5 text-green-600" />
            </div>
            <div>
              <p className="text-sm text-slate-500">Aktiv</p>
              <p className="text-xl font-bold text-slate-900">
                {promotions.filter((p) => p.isActive && !isExpired(p.endDate)).length}
              </p>
            </div>
          </div>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-yellow-50">
              <Clock className="h-5 w-5 text-yellow-600" />
            </div>
            <div>
              <p className="text-sm text-slate-500">Abgelaufen</p>
              <p className="text-xl font-bold text-slate-900">
                {promotions.filter((p) => isExpired(p.endDate)).length}
              </p>
            </div>
          </div>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-purple-50">
              <Sparkles className="h-5 w-5 text-purple-600" />
            </div>
            <div>
              <p className="text-sm text-slate-500">Auto-generiert</p>
              <p className="text-xl font-bold text-slate-900">
                {promotions.filter((p) => p.autoGenerated).length}
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-4 sm:flex-row">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 transform text-slate-400" />
          <input
            type="text"
            placeholder="Aktion suchen..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-10 pr-4 text-slate-900 placeholder-slate-400 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
          />
        </div>
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value as 'all' | 'active' | 'inactive' | 'auto')}
          className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-2 text-slate-900 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
        >
          <option value="all">Alle</option>
          <option value="active">Aktiv</option>
          <option value="inactive">Inaktiv</option>
          <option value="auto">Auto-generiert</option>
        </select>
      </div>

      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="border-b border-slate-200 bg-slate-50">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-medium text-slate-500">Aktion</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-slate-500">Rabatt</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-slate-500">Zeitraum</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-slate-500">Status</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-slate-500">Nutzung</th>
                <th className="px-6 py-4 text-right text-sm font-medium text-slate-500">
                  Aktionen
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredPromotions.map((promotion) => (
                <motion.tr
                  key={promotion.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="transition-colors hover:bg-slate-50/50"
                >
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div
                        className="flex h-10 w-10 items-center justify-center rounded-lg text-sm font-bold text-white"
                        style={{ backgroundColor: promotion.highlightColor || '#4ECCA3' }}
                      >
                        {promotion.badge?.slice(0, 3) || '%'}
                      </div>
                      <div>
                        <p className="flex items-center gap-2 font-medium text-slate-900">
                          {promotion.name}
                          {promotion.autoGenerated && (
                            <Sparkles className="h-4 w-4 text-purple-500" />
                          )}
                        </p>
                        {promotion.bannerText && (
                          <p className="text-sm text-slate-500">{promotion.bannerText}</p>
                        )}
                        {promotion.isCoupon && promotion.code && (
                          <span className="mt-1 inline-flex items-center gap-1.5 rounded-md border border-purple-200 bg-purple-50 px-2 py-0.5 font-mono text-[10px] font-bold tracking-widest text-purple-700">
                            CODE: {promotion.code}
                          </span>
                        )}
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <Percent className="h-4 w-4 text-primary" />
                      <span className="text-slate-900">
                        {promotion.discountType === 'PERCENTAGE'
                          ? `${promotion.discountValue}%`
                          : `${promotion.discountValue}€`}
                      </span>
                    </div>
                    {promotion.isGlobal && <span className="text-xs text-slate-500">Global</span>}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2 text-slate-500">
                      <Calendar className="h-4 w-4" />
                      <span className="text-sm">
                        {new Date(promotion.startDate).toLocaleDateString('de-DE')} -{' '}
                        {new Date(promotion.endDate).toLocaleDateString('de-DE')}
                      </span>
                    </div>
                    {isExpired(promotion.endDate) && (
                      <span className="text-xs text-red-600">Abgelaufen</span>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <button
                      onClick={() => toggleStatus(promotion.id, promotion.isActive)}
                      className={`flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium transition-all ${
                        promotion.isActive && !isExpired(promotion.endDate)
                          ? 'border border-green-200 bg-green-50 text-green-700'
                          : 'border border-slate-200 bg-slate-100 text-slate-500'
                      }`}
                    >
                      {promotion.isActive && !isExpired(promotion.endDate) ? (
                        <>
                          <CheckCircle2 className="h-3 w-3" /> Aktiv
                        </>
                      ) : (
                        <>
                          <XCircle className="h-3 w-3" /> Inaktiv
                        </>
                      )}
                    </button>
                  </td>
                  <td className="px-6 py-4">
                    <span className="text-slate-900">
                      {promotion.usageCount}
                      {promotion.usageLimit && ` / ${promotion.usageLimit}`}
                    </span>
                    <span className="ml-1 text-xs text-slate-500">Nutzungen</span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center justify-end gap-2">
                      <Link
                        href={`/admin/promotions/${promotion.id}/edit`}
                        className="rounded-lg p-2 text-slate-400 transition-all hover:bg-primary/10 hover:text-primary"
                      >
                        <Edit2 className="h-4 w-4" />
                      </Link>
                      <button
                        onClick={() => handleDelete(promotion.id)}
                        className="rounded-lg p-2 text-slate-400 transition-all hover:bg-red-50 hover:text-red-600"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
        {filteredPromotions.length === 0 && (
          <div className="py-12 text-center">
            <AlertCircle className="mx-auto mb-4 h-12 w-12 text-slate-400" />
            <p className="text-slate-500">Keine Aktionen gefunden</p>
          </div>
        )}
      </div>
    </div>
  )
}
